# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install Python setup tools
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            python3 -m pip install setuptools
          else
            brew install python-setuptools
          fi
        shell: bash
      - name: Install packages
        run: |
          pnpm install
        shell: bash
      - name: Build project
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            pnpm run build:ci:win
          else
            pnpm run build:ci:macos
          fi
        shell: bash
      - name: Upload DMG (macOS x86_64)
        uses: actions/upload-artifact@v3
        with:
          name: tidalRPC-${{ matrix.os }}
          path: app/tidalRPC-mac-x64.dmg
        if: matrix.os == 'macos-latest'
      - name: Upload DMG (macOS arm64)
        uses: actions/upload-artifact@v3
        with:
          name: tidalRPC-${{ matrix.os }}
          path: app/tidalRPC-mac-arm64.dmg
        if: matrix.os == 'macos-latest'
      - name: Upload Installer (Windows)
        uses: actions/upload-artifact@v3
        with:
          name: tidalRPC-${{ matrix.os }}
          path: app/tidalRPC-installer.exe
        if: matrix.os == 'windows-latest'
